spring.application.name=ChatApp

spring.security.user.name = user
spring.security.user.password = hello

spring.datasource.url = jdbc:postgresql://ep-curly-mode-a9ng049z.gwc.azure.neon.tech/neondb?sslmode=require
spring.datasource.username = neondb_owner
spring.datasource.password = ${DB_PASSWORD}